version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=dihub
      - POSTGRES_USER=nasph
      - POSTGRES_PASSWORD=Nasph@123
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: